#############################################################################
# Makefile for building: cs3307_project
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  cs3307_project.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile cs3307_project.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++17 -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cs3307_project1.0.0
DISTDIR = /home/hassan/group33/.tmp/cs3307_project1.0.0
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/Login.cpp \
		src/Account.cpp \
		src/Transaction.cpp \
		gui/mainwindow.cpp \
		src/Budget.cpp \
		src/History.cpp qrc_resources.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		Login.o \
		Account.o \
		Transaction.o \
		mainwindow.o \
		Budget.o \
		History.o \
		qrc_resources.o \
		moc_mainwindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cs3307_project.pro src/Login.h \
		src/Account.h \
		src/Transaction.h \
		gui/mainwindow.h \
		src/Budget.h \
		src/History.h src/main.cpp \
		src/Login.cpp \
		src/Account.cpp \
		src/Transaction.cpp \
		gui/mainwindow.cpp \
		src/Budget.cpp \
		src/History.cpp
QMAKE_TARGET  = cs3307_project
DESTDIR       = 
TARGET        = cs3307_project


first: all
####### Build rules

cs3307_project: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cs3307_project.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cs3307_project.pro \
		gui/resources.qrc
	$(QMAKE) -o Makefile cs3307_project.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
cs3307_project.pro:
gui/resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile cs3307_project.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile cs3307_project

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents gui/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/Login.h src/Account.h src/Transaction.h gui/mainwindow.h src/Budget.h src/History.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/Login.cpp src/Account.cpp src/Transaction.cpp gui/mainwindow.cpp src/Budget.cpp src/History.cpp $(DISTDIR)/
	$(COPY_FILE) --parents gui/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: gui/resources.qrc \
		/usr/lib/qt5/bin/rcc \
		gui/chase.png
	/usr/lib/qt5/bin/rcc -name resources gui/resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	clang++ -pipe -std=c++17 -g -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: gui/mainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainertools_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QLineEdit \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlineedit.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpen.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextoption.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QPushButton \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qpushbutton.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractbutton.h \
		src/Login.h \
		src/Account.h \
		src/Budget.h \
		src/History.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hassan/group33/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I/home/hassan/group33 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include gui/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: gui/mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainertools_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qeventloop.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qguiapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qinputmethod.h \
		gui/mainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QLineEdit \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlineedit.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpen.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextoption.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QPushButton \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qpushbutton.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractbutton.h \
		src/Login.h \
		src/Account.h \
		src/Budget.h \
		src/History.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

Login.o: src/Login.cpp src/Login.h \
		src/Account.h \
		src/Budget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Login.o src/Login.cpp

Account.o: src/Account.cpp src/Account.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Account.o src/Account.cpp

Transaction.o: src/Transaction.cpp src/Transaction.h \
		src/Account.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Transaction.o src/Transaction.cpp

mainwindow.o: gui/mainwindow.cpp gui/mainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainertools_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QLineEdit \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlineedit.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpen.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextoption.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QPushButton \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qpushbutton.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractbutton.h \
		src/Login.h \
		src/Account.h \
		src/Budget.h \
		src/History.h \
		ui_mainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/QVariant \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qeventloop.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qguiapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qinputmethod.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QComboBox \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qcombobox.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstyleoption.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvalidator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregularexpression.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qslider.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractslider.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstyle.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabbar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qrubberband.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QFormLayout \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qformlayout.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QLayout \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlayout.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlayoutitem.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qboxlayout.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qgridlayout.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QGridLayout \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QGroupBox \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qgroupbox.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QHBoxLayout \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QHeaderView \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qheaderview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QLabel \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlabel.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QListWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlistwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlistview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QStackedWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstackedwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QTableWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtablewidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtableview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QVBoxLayout \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMessageBox \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmessagebox.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o gui/mainwindow.cpp

Budget.o: src/Budget.cpp src/Budget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Budget.o src/Budget.cpp

History.o: src/History.cpp src/History.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o History.o src/History.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

